library(lubridate)
library(ggplot2)
library(data.table)
library(reshape2)
path <- getwd()
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
zfPath <- file.path(path, "household_power_consumption.zip")
zfPath
if(!file.exists(zfPath)){
  download.file(url, zfPath)
  unzip(zfPath)
}
fPath <- file.path(path, "household_power_consumption.txt")
hpc <- data.table(read.table(fPath, sep = ";", header = TRUE, na.strings = "?"))
hpc <- subset(hpc, hpc$Date == "1/2/2007" | hpc$Date == "2/2/2007")
hpc$datetime <- paste(hpc$Date, hpc$Time)
hpc$datetime <- dmy_hms(hpc$datetime)
dim(hpc)
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(hpc, plot(Global_active_power~datetime, type="l", ylab="Global Active Power", xlab=""))
with(hpc, plot(Voltage~datetime, type="l", ylab="Voltage", xlab=""))
with(hpc, plot(Sub_metering_1~datetime, type="l", ylab="Energy sub metering", xlab=""))
with(hpc, lines(Sub_metering_2~datetime,col='Red'))
with(hpc, lines(Sub_metering_3~datetime,col='Blue'))
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(hpc, plot(Global_reactive_power~datetime, type="l", ylab="Global_rective_power",xlab=""))
dev.off()
